export enum actionsTypes {
  changePostsStatus = 'CHANGE_POSTS_STATUS',
  changeCommentsStatus = 'CHANGE_COMMENTS_STATUS',
  changeAllPostsPage = 'CHANGE_ALL_POSTS_PAGE',
  fetchAllPosts = 'FETCH_ALL_POSTS',
  setPosts = 'SET_ALL_POSTS',
  fetchComments = 'FETCH_COMMENTS',
  setComments = 'SET_COMMENTS',
  changeIdForCommentsFetching = 'CHANGE_ID_FOR_COMMENTS_CHANGING',
  setCurrentUserId = 'SET_CURRENT_USER_ID',
  setUserInfo = 'SET_USER_INFO',
  changeSortOrder = 'CHANGE_SORT_ORDER',
  changeSearchQuery = 'CHANGE_SEARCH_QUERY',
  clearSearchQuery = 'CLEAR_SEARCH_QUERY',
}
